workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
    triggering:
      events:                       
        - push
        - pull_request
        - pull_request_labeled
        - tag
    scripts:
      - name: Cache Flutter Dependencies
        script: |
          flutter pub get
      - name: Build APK with Flutter (No Code Signing)
        script: |
          flutter build apk --debug  # Debug APK for testing
      - name: Build Release APK
        script: |
          flutter build apk --release  # Release APK for distribution
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - eshetieyabibal@gmail.com
        notify:
          success: true
          failure: true
      slack:
        channel: "#ci-cd-notifications"
        notify_on_build_start: true
        notify:
          success: true
          failure: true
          # Customize your Slack notification message in Codemagic UI
